const state={files:[],artifacts:[],run:null,split:"train",metrics:[],visible:new Set()};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function toast(message){const el=$("#toast");el.textContent=message;el.style.display="block";setTimeout(()=>el.style.display="none",2600)}
async function api(path){const response=await fetch(path);const data=await response.json();if(!response.ok)throw new Error(data.error||"请求失败");return data}
function esc(value){return String(value).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}

$$("nav button").forEach(button=>button.onclick=()=>{$$("nav button").forEach(x=>x.classList.remove("active"));button.classList.add("active");$$(".view").forEach(x=>x.classList.remove("active"));$("#"+button.dataset.view).classList.add("active")});

async function refreshStatus(){try{const data=await api("/api/status");$(".connection").classList.add("ok");$("#connection").textContent="服务器在线 · 只读";$("#branch").textContent=data.project.branch||"—";$("#commit").textContent=data.project.commit||"—";$("#repo-status").textContent=data.project.status||"—";$("#gpu-grid").classList.remove("skeleton");$("#gpu-grid").innerHTML=data.gpus.map(g=>`<article class="gpu"><div class="gpu-top"><h3>${esc(g.name)}</h3><span class="gpu-index">GPU ${g.index}</span></div><div class="bar"><i style="width:${g.memoryPercent}%"></i></div><div class="gpu-stats"><div><small>显存</small><strong>${(g.memoryUsed/1024).toFixed(1)} / ${(g.memoryTotal/1024).toFixed(0)} GB</strong></div><div><small>利用率</small><strong>${g.utilization.toFixed(0)}%</strong></div><div><small>温度 / 功耗</small><strong>${g.temperature.toFixed(0)}° · ${g.power.toFixed(0)}W</strong></div></div></article>`).join("")}catch(error){$(".connection").classList.remove("ok");$("#connection").textContent="服务器连接失败";toast(error.message)}}

function renderTree(){const q=$("#file-filter").value.toLowerCase();$("#tree").innerHTML=state.files.filter(path=>path.toLowerCase().includes(q)).map(path=>`<button data-path="${esc(path)}">⌁ ${esc(path)}</button>`).join("");$$("#tree button").forEach(button=>button.onclick=async()=>{try{$$("#tree button").forEach(x=>x.classList.remove("active"));button.classList.add("active");const data=await api("/api/file?path="+encodeURIComponent(button.dataset.path));$("#code-path").textContent=data.path;$("#code-content").textContent=data.content}catch(error){toast(error.message)}})}

function groupRuns(files){const map=new Map();files.forEach(path=>{const marker="/metrics.jsonl";if(path.endsWith(marker)){const root=path.slice(0,-marker.length);map.set(root,{root,metrics:path,files:files.filter(x=>x.startsWith(root+"/"))})}});return [...map.values()]}
async function loadRun(root){const run=state.runs.find(x=>x.root===root);if(!run)return;const payload=await api("/api/artifact?path="+encodeURIComponent(run.metrics));state.run=run;state.metrics=payload.content.split(/\r?\n/).filter(Boolean).map(line=>{try{return JSON.parse(line)}catch{return null}}).filter(Boolean);const keys=[...new Set(state.metrics.flatMap(row=>Object.entries(row).filter(([k,v])=>typeof v==="number"&&k!=="epoch").map(([k])=>k)))].slice(0,8);state.visible=new Set(keys.slice(0,4));$("#metric-toggles").innerHTML=keys.map(key=>`<button class="${state.visible.has(key)?"active":""}" data-key="${esc(key)}">${esc(key)}</button>`).join("");$$("#metric-toggles button").forEach(button=>button.onclick=()=>{state.visible.has(button.dataset.key)?state.visible.delete(button.dataset.key):state.visible.add(button.dataset.key);button.classList.toggle("active");drawChart()});drawChart();renderGallery()}
function drawChart(){const svg=$("#chart"),keys=[...state.visible],rows=state.metrics.filter(r=>Number.isFinite(r.epoch)),colors=["#5ce1a6","#b8f36a","#f3bb63","#71b7ff","#d791ff","#ff7c83","#69e0dd","#d7d7d7"];const vals=rows.flatMap(r=>keys.map(k=>r[k]).filter(Number.isFinite));if(!vals.length){svg.innerHTML='<text x="45" y="80" fill="#87a49a">暂无可绘制指标</text>';return}const W=1100,H=420,p=48,lo=Math.min(...vals),hi=Math.max(...vals)+(Math.max(...vals)===lo?1:0),epochs=rows.map(r=>r.epoch),emin=Math.min(...epochs),emax=Math.max(...epochs),x=e=>p+(e-emin)/Math.max(1,emax-emin)*(W-p*2),y=v=>H-p-(v-lo)/(hi-lo)*(H-p*2);let html=`<line x1="${p}" y1="${H-p}" x2="${W-p}" y2="${H-p}" stroke="#27453e"/><line x1="${p}" y1="${p}" x2="${p}" y2="${H-p}" stroke="#27453e"/>`;keys.forEach((key,i)=>{const splitRows={};rows.filter(r=>Number.isFinite(r[key])).forEach(r=>(splitRows[r.split||"series"]??=[]).push(r));Object.values(splitRows).forEach(group=>html+=`<polyline points="${group.map(r=>`${x(r.epoch)},${y(r[key])}`).join(" ")}" fill="none" stroke="${colors[i%colors.length]}" stroke-width="2"/>`)});svg.innerHTML=html;const last=state.metrics.at(-1)||{};$("#metric-summary").innerHTML=Object.entries(last).filter(([,v])=>typeof v==="number").map(([k,v])=>`<div class="metric-row"><span>${esc(k)}</span><strong>${v.toFixed(5)}</strong></div>`).join("")}
function renderGallery(){if(!state.run){$("#gallery").innerHTML='<div class="empty">选择实验后显示样本</div>';return}const images=state.run.files.filter(path=>/\.(png|jpe?g|webp)$/i.test(path)&&path.toLowerCase().includes(state.split));$("#gallery").innerHTML=images.length?images.map(path=>`<article class="sample"><img loading="lazy" src="/api/image?path=${encodeURIComponent(path)}" alt="${esc(path)}"><p>${esc(path.split("/").pop())}</p></article>`).join(""):'<div class="empty">该实验还没有符合命名约定的 '+state.split+' 固定样本图像</div>'}

async function init(){refreshStatus();setInterval(refreshStatus,10000);try{state.files=(await api("/api/tree")).files;renderTree();$("#file-filter").oninput=renderTree}catch(error){toast(error.message)}try{state.artifacts=(await api("/api/experiments")).files;state.runs=groupRuns(state.artifacts);$("#run-select").innerHTML=state.runs.map(run=>`<option value="${esc(run.root)}">${esc(run.root)}</option>`).join("");$("#run-select").onchange=()=>loadRun($("#run-select").value);if(state.runs.length)loadRun(state.runs[0].root);else{$("#run-select").innerHTML="<option>暂无实验</option>";drawChart();renderGallery()}}catch(error){toast(error.message)}}
$$(".split-tabs button").forEach(button=>button.onclick=()=>{$$(".split-tabs button").forEach(x=>x.classList.remove("active"));button.classList.add("active");state.split=button.dataset.split;renderGallery()});
init();
